Sales Section
MaddozS/punto-de-venta-frontend pull request #1
Opened 2021-06-23 06:41 UTC by alanmoraales

### What it does
- adds sales section
- adds a set of useful components and utills

### Preview
![oQHd5uPIZ4](https://user-images.githubusercontent.com/51354540/123048325-e476b380-d3c3-11eb-8123-d48c55f95638.png)

2021-06-23 15:33 UTC, MaddozS requested changes

2021-06-23 15:33 UTC, MaddozS commented on renderer/components/organisms/CartProductsTable/CartProductsTable.tsx
> +];
Esto debe ser manejado desde el page, el componente no debe manejar información si no es información que deba ser usada en todas sus instancias

2021-06-23 15:33 UTC, MaddozS commented on renderer/components/organisms/CartResumeCard/CartResumeCard.tsx
> +];
Lo mismo que el componente anterior

2021-06-23 15:33 UTC, MaddozS commented on renderer/components/organisms/NewSaleForm/NewSaleForm.tsx
> +export default NewSaleForm;
Solo es un form simbólico? al final no veo ni una forma (ni mediante props) en la cuál comunicar la información del componente a otro, ni viseversa.

Toma en cuenta aqui cada que agregue un producto, también tendré que seleccionar a un cliente, creo que estaría bien separar el ComboBox de cliente a su propio form, o hacer este componente no dependa de un formulario como tal, y al final en el componente de la pagina o en otro lado manejar ahi la info, ojo, solo manejarla

2021-06-23 15:33 UTC, MaddozS commented on renderer/components/templates/MainLayout/MainLayout.tsx
> +export default MainLayout
Solo existe por existir, no tiene utilidad, ni los hijos se le pasan para que se pongan dentro del div

2021-06-24 01:04 UTC, alanmoraales commented on renderer/components/organisms/CartProductsTable/CartProductsTable.tsx
> +];
Era para tener algo que renderizar nada más. Aún así, esa información la voy a traer de un context ahí mismo en el componente CartProductsTable, como ese componente solo lo voy a usar dentro del módulo de ventas, entonces no veo problema en tenerlo ahí en lugar de pasarlo como props

2021-06-24 01:04 UTC, alanmoraales commented on renderer/components/organisms/CartResumeCard/CartResumeCard.tsx
> +];
Lo mismo que el componente anterior x2

2021-06-24 01:06 UTC, alanmoraales commented on renderer/components/organisms/NewSaleForm/NewSaleForm.tsx
> +export default NewSaleForm;
así, solo es el layout, la lógica la pondré en otro pr

2021-06-24 01:07 UTC, alanmoraales commented on renderer/components/templates/MainLayout/MainLayout.tsx
> +export default MainLayout
Ahí va a ir el sidebar, se me olvidó y saqué esta branch de la branch de Itzel, entonces se quedó ese cambio jajaja, pero servirá

2021-06-24 01:44 UTC, MaddozS approved these changes

2021-06-24 03:01 UTC, merged